In [ ]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
### sentences
sent=['the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good',]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
# Define the vocablary size
voc_size=10000

In [6]:
# One Hot Representation for every word
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[9843, 7097, 4549, 2826],
 [9843, 7097, 4549, 8536],
 [9843, 1909, 4549, 4741],
 [400, 7800, 871, 7, 9904],
 [400, 7800, 871, 7, 3138],
 [7180, 9843, 180, 4549, 4440],
 [7169, 9340, 9504, 7]]

In [16]:
# Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Input, Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


import numpy as np 

In [10]:
# To sent the sentences to the model they should be of same length or fix length hence use pad_sequences

sent_length = 8 # max sentence length
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
# To make the sentences of same length the pad_sequence will add 0s in the end(post) or in the start(pre)
print(embedded_docs)


[[   0    0    0    0 9843 7097 4549 2826]
 [   0    0    0    0 9843 7097 4549 8536]
 [   0    0    0    0 9843 1909 4549 4741]
 [   0    0    0  400 7800  871    7 9904]
 [   0    0    0  400 7800  871    7 3138]
 [   0    0    0 7180 9843  180 4549 4440]
 [   0    0    0    0 7169 9340 9504    7]]


In [11]:
# Feature Represenation

dim = 10

In [ ]:
# Embedding Layer internally using Word2Vec, No training Needed

model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size, dim))
model.compile('adam', 'mse')

In [18]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
# every word will be represented as 10 dimension

model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step


array([[[-3.5357960e-03, -2.0784641e-02, -1.9793630e-02, -4.1122615e-02,
          1.8027496e-02,  2.0477716e-02,  3.5690654e-02,  4.2949107e-02,
          5.3244345e-03,  4.2358637e-03],
        [-3.5357960e-03, -2.0784641e-02, -1.9793630e-02, -4.1122615e-02,
          1.8027496e-02,  2.0477716e-02,  3.5690654e-02,  4.2949107e-02,
          5.3244345e-03,  4.2358637e-03],
        [-3.5357960e-03, -2.0784641e-02, -1.9793630e-02, -4.1122615e-02,
          1.8027496e-02,  2.0477716e-02,  3.5690654e-02,  4.2949107e-02,
          5.3244345e-03,  4.2358637e-03],
        [-3.5357960e-03, -2.0784641e-02, -1.9793630e-02, -4.1122615e-02,
          1.8027496e-02,  2.0477716e-02,  3.5690654e-02,  4.2949107e-02,
          5.3244345e-03,  4.2358637e-03],
        [ 3.4212247e-03, -4.3930698e-02, -3.1095386e-02,  2.1850977e-02,
          4.5260143e-02, -2.5882781e-02,  2.7101923e-02,  4.6543691e-02,
         -3.6403500e-02, -2.6658166e-02],
        [-5.2636266e-03,  3.9382603e-02, -4.8728101e-03,  3.